### ISSUE TITLE
About dialog story not working

### ISSUE THREAD

**Issue by stropitek** [zakodium-oss/react-science#705]
https://react-science.pages.dev/stories/?path=/story/components-aboutdialogtoolbarbutton--display-about-dialog

**Comment by wadjih-bencheikh18** [comment]
I found that the problem is in `ms-spectrum`
https://github.com/zakodium-oss/react-science/blob/d564f514631ceaa18fef49da7ba2d3e31af5a26b/src/app/kinds/mass/MeasurementMassPlot.tsx#L3

When I comment this line everything works.
Do have any idea what can be the problem in the package? https://github.com/cheminfo/mass-tools
here's the error we're getting:
```
Cannot read properties of undefined (reading 'prototype')
```

**Comment by stropitek** [comment]
Which one is problematic (`Spectrum` or `getBestPeaks`)?

**Comment by targos** [comment]
Maybe I'm mixing things up, but I think it was related to https://github.com/zakodium-oss/react-science/issues/685
